disabled_rules: # rule identifiers to exclude from running
  - opening_brace
  - nesting
  - large_tuple
  - file_length
  # - trailing_whitespace # remove this later!!!
included: # paths to include during linting. `--path` is ignored if present.
  - Sources

# # configurable rules can be customized from this configuration file
# # binary rules can set their severity level
line_length:
  ignores_comments: true
trailing_whitespace:
  ignores_empty_lines: true
type_name:
  allowed_symbols: _
statement_position:
  statement_mode: uncuddled_else # https://github.com/realm/SwiftLint/issues/1181#issuecomment-272445593
